/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright(c) 2018 Fast River Technologies Inc. All Rights Reserved.
 * 
 * $Date:                             
 * $Revision:                         
 * $Author:                                         
 * $Id: 
 */ 

CREATE INDEX RESOURCE_IDX1 ON RESOURCE(id);

CREATE INDEX PATIENT_IDX1 ON PATIENT(gender);
CREATE INDEX PATIENT_IDX2 ON PATIENT(birthDate);

CREATE INDEX PATIENT_EXTENSION_IDX1 ON PATIENT_EXTENSION(path, resource_id);

CREATE INDEX PATIENT_IDENTIFIER_IDX1 ON PATIENT_IDENTIFIER(path, resource_id);
CREATE INDEX PATIENT_IDENTIFIER_IDX2 ON PATIENT_IDENTIFIER(use, system);

CREATE INDEX PATIENT_HUMANNAME_IDX1 ON PATIENT_HUMANNAME(path, resource_id);
CREATE INDEX PATIENT_HUMANNAME_IDX2 ON PATIENT_HUMANNAME(path, given);
CREATE INDEX PATIENT_HUMANNAME_IDX3 ON PATIENT_HUMANNAME(given, family);

CREATE INDEX PATIENT_CONTACTPOINT_IDX1 ON PATIENT_CONTACTPOINT(path, resource_id);

CREATE INDEX PATIENT_ADDRESS_IDX1 ON PATIENT_ADDRESS(path, resource_id);
CREATE INDEX PATIENT_ADDRESS_IDX2 ON PATIENT_ADDRESS(line);
CREATE INDEX PATIENT_ADDRESS_IDX3 ON PATIENT_ADDRESS(city);
CREATE INDEX PATIENT_ADDRESS_IDX4 ON PATIENT_ADDRESS(state);
CREATE INDEX PATIENT_ADDRESS_IDX5 ON PATIENT_ADDRESS(city, state);

CREATE INDEX PATIENT_CODEABLECONCEPT_IDX1 ON PATIENT_CODEABLECONCEPT(path, resource_id);

CREATE INDEX PATIENT_ATTACHMENT_IDX1 ON PATIENT_ATTACHMENT(path, resource_id);

CREATE INDEX PATIENT_CONTACT_IDX1 ON PATIENT_CONTACT(name);


