/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright(c) 2018 Fast River Technologies Inc. All Rights Reserved.
 * 
 * $Date:                             
 * $Revision:                         
 * $Author:                                         
 * $Id: 
 */ 
-- drop FHIR patient resource relevant tables --
DROP TABLE PATIENT_IDENTIFIER IF EXISTS;
DROP TABLE PATIENT_HUMANNAME IF EXISTS;
DROP TABLE PATIENT_CONTACTPOINT IF EXISTS;
DROP TABLE PATIENT_ADDRESS IF EXISTS;
DROP TABLE PATIENT_CODEABLECONCEPT IF EXISTS;
DROP TABLE PATIENT_ATTACHMENT IF EXISTS;
DROP TABLE PATIENT_CONTACT IF EXISTS;
DROP TABLE PATIENT_ANIMAL IF EXISTS;
DROP TABLE PATIENT_COMMUNICATION IF EXISTS;
DROP TABLE PATIENT_REFERENCE IF EXISTS;
DROP TABLE PATIENT_LINK IF EXISTS;
DROP TABLE PATIENT_EXTENSION IF EXISTS;
DROP TABLE PATIENT_ELEMENT_EXTENSION IF EXISTS;
DROP TABLE PATIENT IF EXISTS;

 -- drop system tables --
DROP TABLE DOMAIN_RESOURCE IF EXISTS;
DROP TABLE RESOURCE IF EXISTS;
DROP TABLE SYSTEM_RESOURCE IF EXISTS;

-- drop sequences --
DROP SEQUENCE PATIENT_IDENTIFIER_SEQ RESTRICT;
DROP SEQUENCE PATIENT_HUMANNAME_SEQ RESTRICT;
DROP SEQUENCE PATIENT_SEQ RESTRICT;
