/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright(c) 2018 Fast River Technologies Inc. All Rights Reserved.
 * 
 * $Date:                             
 * $Revision:                         
 * $Author:                                         
 * $Id: 
 */ 

DROP INDEX RESOURCE_IDX1;

DROP INDEX PATIENT_IDX1;
DROP INDEX PATIENT_IDX2;

DROP INDEX PATIENT_EXTENSION_IDX1;

DROP INDEX PATIENT_IDENTIFIER_IDX1;
DROP INDEX PATIENT_IDENTIFIER_IDX2;

DROP INDEX PATIENT_HUMANNAME_IDX1;
DROP INDEX PATIENT_HUMANNAME_IDX2;
DROP INDEX PATIENT_HUMANNAME_IDX3;

DROP INDEX PATIENT_CONTACTPOINT_IDX1;

DROP INDEX PATIENT_ADDRESS_IDX1;
DROP INDEX PATIENT_ADDRESS_IDX2;
DROP INDEX PATIENT_ADDRESS_IDX3;
DROP INDEX PATIENT_ADDRESS_IDX4;
DROP INDEX PATIENT_ADDRESS_IDX5;

DROP INDEX PATIENT_CODEABLECONCEPT_IDX1;

DROP INDEX PATIENT_ATTACHMENT_IDX1;

DROP INDEX PATIENT_CONTACT_IDX1;
