/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright(c) 2018 Fast River Technologies Inc. All Rights Reserved.
 * 
 * $Date:                             
 * $Revision:                         
 * $Author:                                         
 * $Id: 
 */ 
 -- drop FHIR observation resource relevant tables --
DROP TABLE OBSERVATION_IDENTIFIER IF EXISTS;
DROP TABLE OBSERVATION_CODEABLECONCEPT IF EXISTS;
DROP TABLE OBSERVATION_REFERENCE IF EXISTS;
DROP TABLE OBSERVATION_REFERENCERANGE IF EXISTS;
DROP TABLE OBSERVATION_RELATED IF EXISTS;
DROP TABLE OBSERVATION_COMPONENT IF EXISTS;
DROP TABLE OBSERVATION_ELEMENT_EXTENSION IF EXISTS;
DROP TABLE OBSERVATION_EXTENSION IF EXISTS;
DROP TABLE OBSERVATION IF EXISTS;
