/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright(c) 2018 Fast River Technologies Inc. All Rights Reserved.
 * 
 * $Date:                             
 * $Revision:                         
 * $Author:                                         
 * $Id: 
 */ 
-- truncate FHIR patient resource relevant tables --
TRUNCATE TABLE PATIENT_IDENTIFIER;
TRUNCATE TABLE PATIENT_HUMANNAME;
TRUNCATE TABLE PATIENT_CONTACTPOINT;
TRUNCATE TABLE PATIENT_ADDRESS;
TRUNCATE TABLE PATIENT_CODEABLECONCEPT;
TRUNCATE TABLE PATIENT_ATTACHMENT;
TRUNCATE TABLE PATIENT_CONTACT;
TRUNCATE TABLE PATIENT_ANIMAL;
TRUNCATE TABLE PATIENT_COMMUNICATION;
TRUNCATE TABLE PATIENT_REFERENCE;
TRUNCATE TABLE PATIENT_LINK;
TRUNCATE TABLE PATIENT_EXTENSION;
-- truncate patient transaction table --
TRUNCATE TABLE PATIENT_TRANSACTION;
-- truncate primary patient table --
TRUNCATE TABLE PATIENT;

-- truncate system tables --
TRUNCATE TABLE DOMAIN_RESOURCE;
TRUNCATE TABLE RESOURCE;
