{
 "title": "FHIR Patient By Organization ( FHIR Stream )",
 "description": "FHIR Patient By Organizations",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FHIR  Patient  Count Grouped By Health Organization",
   "type": "grafana-groupedbarchart-panel",
   "description": "Dynamically computing from FHIR  message streams, FHIR  Patient  Count (M/F) Grouped By Health Organization",
   "gridPos": { "h": 21, "w": 14, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(ORG_ID, \":\", FHIR_ORG.NAME) AS metric,\n  PATIENT_GENDER,\n  MAX(CNT)\nFROM FHIR_GROUPBY_ORG_GENDER, FHIR_ORG \nWHERE\nFHIR_GROUPBY_ORG_GENDER.ORG_ID=FHIR_ORG.ID \nGROUP BY FHIR_GROUPBY_ORG_GENDER.ORG_ID, FHIR_ORG.NAME, PATIENT_GENDER\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Total FHIR Patients  By Hospitals",
   "type": "grafana-piechart-panel",
   "description": "Dynamically computing from real-time FHIR message streaming, Total FHIR Patients  By Hospitals",
   "gridPos": { "h": 13, "w": 9, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT A.TS AS \"time\",   \r\n       A.ORG_UNIQ_NAME AS metrics,   \r\n\t   SUM(A.CNT) \r\nFROM (SELECT CURRENT_TIMESTAMP AS TS, CONCAT(ORG_ID, \"-\", FHIR_ORG.NAME) AS ORG_UNIQ_NAME, PATIENT_GENDER, max(CNT) AS CNT     \r\n\t  FROM FHIR_GROUPBY_ORG_GENDER, FHIR_ORG\r\n\t  WHERE FHIR_GROUPBY_ORG_GENDER.ORG_ID=FHIR_ORG.ID\r\n\t  GROUP BY ORG_UNIQ_NAME, PATIENT_GENDER) AS A \r\nGROUP BY ORG_UNIQ_NAME, TS;\r\n\r\n"
    }
   ]
  },
  {
   "title": "FHIR Health Organizations",
   "type": "table",
   "description": "Dynamically updating the FHIR Health Organizations",
   "gridPos": { "h": 10, "w": 9, "x": 14, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  ID,\n  NAME,\n  TELECOM,\n  ADDRESSLINE,\n  CITY,\n  STATE,\n  POSTALCODE\nFROM FHIR_ORG\nORDER BY ID"
    }
   ]
  }
 ]
}