{
 "title": "FHIR Patient By State ( FHIR Stream )",
 "description": "FHIR Patient Grouped by State",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "FHIR Patient Count By State in Time Series",
   "type": "graph",
   "description": "FHIR Patient Count By State in Time Series",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Patient Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  CONCAT(ADDR_STATE, \":\", PATIENT_GENDER) AS metric,\n  MAX(CNT)\nFROM FHIR_GROUPBY_STATE_SINK\nGROUP BY ADDR_STATE, PATIENT_GENDER, TS\nORDER BY TS"
    }
   ]
  },
  {
   "title": "PATIENT TOTAL BY STATES & GENDER",
   "type": "grafana-groupedbarchart-panel",
   "description": "PATIENT TOTAL BY STATES & GENDER",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ADDR_STATE AS metric,\n  PATIENT_GENDER,\n  max(CNT) AS \"TOTAL\"\nFROM FHIR_GROUPBY_STATE_SINK\nGROUP BY ADDR_STATE, PATIENT_GENDER\nORDER BY ADDR_STATE"
    }
   ]
  },
  {
   "title": "PATIENT COUNT BY STATES & GENDER",
   "type": "grafana-piechart-panel",
   "description": "PATIENT COUNT BY STATES",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT $__unixEpochGroupAlias(TS,$__interval),\nCONCAT(ADDR_STATE, \":\", PATIENT_GENDER) AS metric,\nmax(CNT) AS \"CNT\" \nFROM FHIR_GROUPBY_STATE_SINK \nGROUP BY 1, ADDR_STATE,2 \nORDER BY 2, $__unixEpochGroup(TS,$__interval)"
    }
   ]
  }
 ]
}