{
 "title": "FHIR Patient By State ( FHIR Stream )",
 "description": "FHIR Patient Grouped by State",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FHIR Patient Count By State in Time Series",
   "type": "graph",
   "description": "FHIR Patient Count By State in Time Series",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Patient Count" }
   ],
   "targets": [
    {
     "rawSql": "/* display different gender lines\r\nSELECT\r\n  $__unixEpochGroupAlias(TS,$__interval),\r\n  CONCAT(ADDR_STATE, \":\", PATIENT_GENDER) AS \"metric\",\r\n  MAX(CNT)\r\nFROM FHIR_GROUPBY_STATE_GENDER\r\nGROUP BY 1, ADDR_STATE, PATIENT_GENDER\r\nORDER BY ADDR_STATE, $__unixEpochGroup(TS,$__interval)\r\n*/\r\n\r\n/* combined gender lines */\r\nSELECT\r\n  $__unixEpochGroupAlias(C.TS,$__interval),\r\n  C.STATE AS \"metric\",\r\n  C.ACNT + C.BCNT\r\nFROM \r\n(SELECT A.TS AS TS, A.ADDR_STATE AS STATE, A.PATIENT_GENDER AS GENDER, A.CNT AS ACNT, MAX(B.CNT) AS BCNT   \r\n FROM \r\n  (SELECT * FROM FHIR_GROUPBY_STATE_GENDER        \r\n   WHERE PATIENT_GENDER='male') A  \r\n LEFT JOIN        \r\n  (SELECT * FROM FHIR_GROUPBY_STATE_GENDER    \r\n   WHERE PATIENT_GENDER='female') B  \r\n ON (A.ADDR_STATE = B.ADDR_STATE AND A.TS > B.TS)  \r\n GROUP BY A.TS, A.ADDR_STATE, A.PATIENT_GENDER, A.CNT, B.PATIENT_GENDER) C\r\nORDER BY C.STATE, $__unixEpochGroup(C.TS,$__interval)\r\n"
    }
   ]
  },
  {
   "title": "PATIENT TOTAL BY STATES & GENDER",
   "type": "grafana-groupedbarchart-panel",
   "description": "PATIENT TOTAL BY STATES & GENDER",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ADDR_STATE AS metric,\n  PATIENT_GENDER,\n  max(CNT) AS \"TOTAL\"\nFROM FHIR_GROUPBY_STATE_GENDER\nGROUP BY ADDR_STATE, PATIENT_GENDER\nORDER BY ADDR_STATE"
    }
   ]
  },
  {
   "title": "PATIENT COUNT BY STATES",
   "type": "grafana-piechart-panel",
   "description": "PATIENT COUNT BY STATES",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT A.TS AS \"time\",   \r\n       A.ADDR_STATE AS metrics,   \r\n\t   SUM(A.CNT) \r\nFROM (SELECT CURRENT_TIMESTAMP AS TS, ADDR_STATE, PATIENT_GENDER,max(CNT) AS CNT     \r\n\t  FROM FHIR_GROUPBY_STATE_GENDER      \r\n\t  GROUP BY ADDR_STATE, PATIENT_GENDER) AS A \r\nGROUP BY ADDR_STATE, TS;\r\n\r\n"
    }
   ]
  }
 ]
}