{
 "title": "FHIR Patient By Practitioner ( FHIR Stream)",
 "description": "FHIR Patient Count Grouped By Practitioner",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FHIR Patient Count Grouped By Practitioner (FHIR Stream)",
   "type": "grafana-groupedbarchart-panel",
   "description": "FHIR Patient Count Grouped By Practitioner",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(NPI, \":\",  FHIR_GP.NAME) AS metric,\n  PATIENT_GENDER,\n  MAX(CNT)\nFROM FHIR_GROUPBY_GP_GENDER, FHIR_GP\nWHERE FHIR_GROUPBY_GP_GENDER.NPI=FHIR_GP.ID\nGROUP BY FHIR_GROUPBY_GP_GENDER.NPI, FHIR_GP.NAME, FHIR_GROUPBY_GP_GENDER.PATIENT_GENDER\nORDER BY  FHIR_GROUPBY_GP_GENDER.NPI, FHIR_GP.NAME"
    }
   ]
  },
  {
   "title": "FHIR Patient by Practitioner",
   "type": "grafana-piechart-panel",
   "description": "FHIR Patient by Practitioner",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT A.TS AS \"time\",   \r\n       A.GP_UNIQ_NAME AS metrics,   \r\n\t   SUM(A.CNT) \r\nFROM (SELECT CURRENT_TIMESTAMP AS TS, CONCAT(NPI, \"-\", FHIR_GP.NAME) AS GP_UNIQ_NAME, PATIENT_GENDER, max(CNT) AS CNT     \r\n\t  FROM FHIR_GROUPBY_GP_GENDER, FHIR_GP\r\n\t  WHERE FHIR_GROUPBY_GP_GENDER.NPI=FHIR_GP.ID\r\n\t  GROUP BY GP_UNIQ_NAME, PATIENT_GENDER) AS A \r\nGROUP BY GP_UNIQ_NAME, TS;\r\n\r\n"
    }
   ]
  },
  {
   "title": "FHIR Practitioners of Patients",
   "type": "table",
   "description": "A list of practitioners of the Patients",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS NPI,\n  name AS Name,\n  specialty AS Specialty,\n  telecom AS Phone,\n  addressline AS Address,\n  city AS City,\n  state AS State,\n  postalcode AS PostalCode\nFROM FHIR_GP\nORDER BY id"
    }
   ]
  }
 ]
}