{
 "title": "FHIR Patient By Organization",
 "description": "FHIR Patient By Organizations",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FHIR  Patient  Count Grouped By Health Organization",
   "type": "graph",
   "description": "Dynamically computing from FHIR  message streams",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Patient Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  ORG_ID AS metric,\n  CNT\nFROM FHIR_GROUPBY_ORG_SINK\nWHERE\n  $__timeFilter(TS)\nORDER BY TS"
    }
   ]
  },
  {
   "title": "Total FHIR Patients ",
   "type": "grafana-piechart-panel",
   "description": "Dynamically computing from real-time FHIR message streaming",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  PATIENT_GENDER AS metric,\n  CNT\nFROM FHIR_GROUPBY_ORG_SINK\nWHERE\n  $__timeFilter(TS)\nORDER BY TS"
    }
   ]
  },
  {
   "title": "FHIR Health Organizations",
   "type": "table",
   "description": "Dynamically updating the FHIR Health Organizations",
   "gridPos": { "h": 5, "w": 13, "x": 5, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  ID,\n  NAME,\n  TELECOM,\n  ADDRESSLINE,\n  CITY,\n  STATE,\n  POSTALCODE\nFROM FHIR_ORG_SINK\nORDER BY ID"
    }
   ]
  }
 ]
}