{
 "title": "FHIR Patient By State ( FHIR Stream )",
 "description": "FHIR Patient Grouped by State",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "FHIR Patient Count By State in Time Series",
   "type": "graph",
   "description": "FHIR Patient Count By State in Time Series",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Patient Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  ADDR_STATE AS metric,\n  CNT\nFROM FHIR_GROUPBY_STATE_SINK\nORDER BY TS"
    }
   ]
  },
  {
   "title": "PATIENT TOTAL BY STATES & GENDER",
   "type": "grafana-groupedbarchart-panel",
   "description": "PATIENT TOTAL BY STATES & GENDER",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ADDR_STATE AS metric,\n  PATIENT_GENDER,\n  max(CNT) AS \"TOTAL\"\nFROM FHIR_GROUPBY_STATE_SINK\nGROUP BY ADDR_STATE, PATIENT_GENDER\nORDER BY ADDR_STATE"
    }
   ]
  },
  {
   "title": "PATIENT COUNT BY STATES",
   "type": "grafana-piechart-panel",
   "description": "PATIENT COUNT BY STATES",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(TS,$__interval),\n  ADDR_STATE AS metric,\n  max(CNT) AS \"CNT\"\nFROM FHIR_GROUPBY_STATE_SINK\nGROUP BY 1, ADDR_STATE,2\nORDER BY $__unixEpochGroup(TS,$__interval)"
    }
   ]
  }
 ]
}