{
 "title": "FHIR Patient By Organization ( FHIR Stream )",
 "description": "FHIR Patient By Organizations",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FHIR  Patient  Count Grouped By Health Organization",
   "type": "grafana-groupedbarchart-panel",
   "description": "Dynamically computing from FHIR  message streams",
   "gridPos": { "h": 19, "w": 14, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(ORG_ID, \":\", FHIR_ORG_SINK.NAME) AS metric,\n  PATIENT_GENDER,\n  MAX(CNT)\nFROM FHIR_GROUPBY_ORG_SINK, FHIR_ORG_SINK \nWHERE\nFHIR_GROUPBY_ORG_SINK.ORG_ID=FHIR_ORG_SINK.ID \nGROUP BY FHIR_GROUPBY_ORG_SINK.ORG_ID, FHIR_ORG_SINK.NAME, PATIENT_GENDER\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Total FHIR Patients ",
   "type": "grafana-piechart-panel",
   "description": "Dynamically computing from real-time FHIR message streaming",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  TS AS \"time\",\n  PATIENT_GENDER AS metric,\n  CNT\nFROM FHIR_GROUPBY_ORG_SINK\nWHERE\n  $__timeFilter(TS)\nORDER BY TS"
    }
   ]
  },
  {
   "title": "FHIR Health Organizations",
   "type": "table",
   "description": "Dynamically updating the FHIR Health Organizations",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  ID,\n  NAME,\n  TELECOM,\n  ADDRESSLINE,\n  CITY,\n  STATE,\n  POSTALCODE\nFROM FHIR_ORG_SINK\nORDER BY ID"
    }
   ]
  }
 ]
}