DROP TABLE IF EXISTS FHIR_GROUPBY_ORG_SINK;
DROP TABLE IF EXISTS FHIR_GP_SINK;
DROP TABLE IF EXISTS FHIR_GROUPBY_AGE;
DROP TABLE IF EXISTS FHIR_GROUPBY_GP;
DROP TABLE IF EXISTS FHIR_GROUPBY_STATE_SINK;
DROP TABLE IF EXISTS FHIR_ORG_SINK;
