USE FHIR_DB;
# clean up mysql function, triggers, tables for grafana dashboards

DROP TRIGGER IF EXISTS DS_TRIGGER_STATE_GENDER;
DROP FUNCTION IF EXISTS GET_TS_IN_RANGE;

DROP TABLE IF EXISTS FHIR_GROUPBY_STATE_GENDER;
DROP TABLE IF EXISTS FHIR_GROUPBY_GP_GENDER;
DROP TABLE IF EXISTS FHIR_GROUPBY_ORG_GENDER;
DROP TABLE IF EXISTS FHIR_DATE_RANGE;

