/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright(c) 2018 Fast River Technologies Inc. All Rights Reserved.
 * 
 * $Date:                             
 * $Revision:                         
 * $Author:                                         
 * $Id: 
 */ 
 -- drop FHIR observation resource relevant tables --
DROP TABLE OBSERVATION CASCADE CONSTRAINTS;
DROP TABLE OBSERVATION_IDENTIFIER CASCADE CONSTRAINTS;
DROP TABLE OBSERVATION_CODEABLECONCEPT CASCADE CONSTRAINTS;
DROP TABLE OBSERVATION_REFERENCE CASCADE CONSTRAINTS;
DROP TABLE OBSERVATION_REFERENCERANGE CASCADE CONSTRAINTS;
DROP TABLE OBSERVATION_RELATED CASCADE CONSTRAINTS;
DROP TABLE OBSERVATION_COMPONENT CASCADE CONSTRAINTS;
DROP TABLE OBSERVATION_ELEMENT_EXTENSION CASCADE CONSTRAINTS;
