# Clean up mysql FUNCTION, TRIGGERS, TABLES for GRAFANA dashboards
USE FHIR_DB;
DROP TRIGGER IF EXISTS DS_TRIGGER_STATE_GENDER;
DROP FUNCTION IF EXISTS GET_TS_IN_RANGE;
DROP TABLE IF EXISTS FHIR_DATE_RANGE;